# -*- coding: utf-8 -*-
"""Teste CalcArcFlash_IEEE1584 online.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHHxJOCis_gpLsb4usWLubTWDOAnL6Yb
"""

import streamlit as st
import math
import pandas as pd
import numpy as np
from docxtpl import DocxTemplate
import openpyxl
import io

# ==============================================================================
# 1. BACKEND: LÓGICA DE CÁLCULO IEEE 1584-2018
# ==============================================================================
TABLE_1 = {'VCB': [-0.04287, 1.035, -0.083, 0, 0, -4.783e-9, 1.962e-6, -0.000229, 0.003141, 1.092], 'VCBB': [-0.017432, 0.98, -0.05, 0, 0, -5.767e-9, 2.524e-6, -0.00034, 0.01187, 1.013], 'HCB': [0.054922, 0.988, -0.11, 0, 0, -5.382e-9, 2.316e-6, -0.000302, 0.0091, 0.9725], 'VOA': [0.043785, 1.04, -0.18, 0, 0, -4.783e-9, 1.962e-6, -0.000229, 0.003141, 1.092], 'HOA': [0.111147, 1.008, -0.24, 0, 0, -3.895e-9, 1.641e-6, -0.000197, 0.002615, 1.1]}
TABLE_3 = {'VCB': [0.753364, 0.566, 1.752636, 0, 0, -4.783e-9, 1.962e-6, -0.000229, 0.003141, 1.092, 0, -1.598, 0.957], 'VCBB': [3.068459, 0.26, -0.098107, 0, 0, -5.767e-9, 2.524e-6, -0.00034, 0.01187, 1.013, -0.06, -1.809, 1.19], 'HCB': [4.073745, 0.344, -0.370259, 0, 0, -5.382e-9, 2.316e-6, -0.000302, 0.0091, 0.9725, 0, -2.03, 1.036], 'VOA': [0.679294, 0.746, 1.222636, 0, 0, -4.783e-9, 1.962e-6, -0.000229, 0.003141, 1.092, 0, -1.598, 0.997], 'HOA': [3.470417, 0.465, -0.261863, 0, 0, -3.895e-9, 1.641e-6, -0.000197, 0.002615, 1.1, 0, -1.99, 1.04]}
TABLE_7_TYPICAL = {'VCB': [-0.000302, 0.03441, 0.4325], 'VCBB': [-0.0002976, 0.032, 0.479], 'HCB': [-0.0001923, 0.01935, 0.6899]}
TABLE_7_SHALLOW = {'VCB': [0.002222, -0.02556, 0.6222], 'VCBB': [-0.002778, 0.1194, -0.2778], 'HCB': [-0.0005556, 0.03722, 0.4778]}
CONSTANTS_AB = {'VCB':  {'A': 4,  'B': 20}, 'VCBB': {'A': 10, 'B': 24}, 'HCB':  {'A': 10, 'B': 22}}

def log10(x): return math.log10(x) if x > 0 else 0

def calcular_ajuste_linear(dim_mm, Voc_kV, Config):
    if Config not in CONSTANTS_AB: return dim_mm / 25.4
    A, B = CONSTANTS_AB[Config]['A'], CONSTANTS_AB[Config]['B']
    return (660.4 + (dim_mm - 660.4) * ((Voc_kV + A) / B)) * (1 / 25.4)

def calcular_ees_correto(Config, H_mm, W_mm, D_mm, Voc_kV):
    H_in, W_in = H_mm / 25.4, W_mm / 25.4
    if Voc_kV < 0.6 and H_mm < 508 and W_mm < 508 and D_mm <= 203.2: return (H_in + W_in) / 2, "Shallow (Raso)"
    W1 = 20.0 if W_mm < 508 else W_in if W_mm <= 660.4 else calcular_ajuste_linear(W_mm if W_mm <= 1244.6 else 1244.6, Voc_kV, Config)
    if Config == 'VCB':
        H1 = 20.0 if H_mm < 508 else H_in if H_mm <= 1244.6 else 49.0
    elif Config in ['VCBB', 'HCB']:
        H1 = 20.0 if H_mm < 508 else H_in if H_mm <= 660.4 else calcular_ajuste_linear(H_mm if H_mm <= 1244.6 else 1244.6, Voc_kV, Config)
    else:
        H1 = H_in
    return (H1 + W1) / 2, "Typical (Típico)"

def calcular_core_ieee1584(Voc_V, Ibf, Config, Gap, Dist, T_ms, H=600, W=600, D=300):
    Voc = Voc_V / 1000.0
    k = TABLE_1[Config]
    term1 = 10 ** (k[0] + k[1]*log10(Ibf) + k[2]*log10(Gap))
    term2 = (k[3]*Ibf**6 + k[4]*Ibf**5 + k[5]*Ibf**4 + k[6]*Ibf**3 + k[7]*Ibf**2 + k[8]*Ibf + k[9])
    Iarc600 = term1 * term2
    term_a = (0.6/Voc)**2
    term_b = (1/Iarc600)**2 - ((0.6**2 - Voc**2)/(0.6**2 * Ibf**2))
    if term_a * term_b <= 0: return None
    Iarc = 1 / math.sqrt(term_a * term_b)

    if Config in ['VOA', 'HOA']: CF, box = 1.0, "Ar Livre"
    else:
        EES, box = calcular_ees_correto(Config, H, W, D, Voc)
        b = TABLE_7_SHALLOW[Config] if "Shallow" in box else TABLE_7_TYPICAL[Config]
        CF = 1/(b[0]*EES**2 + b[1]*EES + b[2]) if "Shallow" in box else b[0]*EES**2 + b[1]*EES + b[2]

    tk = TABLE_3[Config]
    C2 = tk[3]*Ibf**7 + tk[4]*Ibf**6 + tk[5]*Ibf**5 + tk[6]*Ibf**4 + tk[7]*Ibf**3 + tk[8]*Ibf**2 + tk[9]*Ibf
    C3 = tk[10]*log10(Ibf) + tk[11]*log10(Dist) + log10(1/CF)
    exp = tk[0] + tk[1]*log10(Gap) + (tk[2]*Iarc600/C2) + C3 + tk[12]*log10(Iarc)
    E_joule = (12.552/50)*T_ms*(10**exp)
    return Iarc, E_joule/4.184, Dist * (1.2/(E_joule/4.184))**(1/tk[11]), box

# ==============================================================================
# 2. FRONTEND: STREAMLIT APP
# ==============================================================================
st.set_page_config(page_title="Calc. Energia Incidente", layout="wide")

# CSS para garantir que tudo fique legível no servidor
st.markdown("""
<style>
    .result-card { background-color: #f0f2f6; padding: 20px; border-radius: 10px; border-left: 5px solid #ff4b4b; }
</style>
""", unsafe_allow_html=True)

st.title("⚡ Calculadora de Energia Incidente (IEEE 1584-2018)")
st.markdown("Ferramenta profissional para simulação de **Arc Flash** em Baixa Tensão (< 600V).")

with st.sidebar:
    st.header("⚙️ Equipamento")
    equip_name = st.text_input("Nome do TAG", value="QGBT-01")
    voltage = st.selectbox("Tensão (V)", [220, 380, 440, 480], index=3)
    config_electrode = st.selectbox("Eletrodos", ["VCB", "VCBB", "HCB", "VOA", "HOA"], index=0)
    st.markdown("---")
    st.subheader("Dimensões (mm)")
    dis = config_electrode in ['VOA', 'HOA']
    h_mm = st.number_input("Altura (H)", value=2000, disabled=dis)
    w_mm = st.number_input("Largura (W)", value=800, disabled=dis)
    d_mm = st.number_input("Profundidade (D)", value=400, disabled=dis)

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("🎛️ Parâmetros de Simulação")
    ibf_ka = st.slider("Corrente de Curto (kA)", 1.0, 100.0, 20.0, 0.5)
    gap_mm = st.slider("Gap entre Condutores (mm)", 6.0, 150.0, 32.0, 1.0)
    dist_mm = st.slider("Distância de Trabalho (mm)", 300, 1000, 610, 10)
    time_ms = st.number_input("Tempo de Arco (ms)", 10.0, value=100.0, step=10.0)

res = calcular_core_ieee1584(voltage, ibf_ka, config_electrode, gap_mm, dist_mm, time_ms, h_mm, w_mm, d_mm)

with col2:
    st.subheader("📊 Resultados")
    if res:
        i_arc, energy, afb, box_type = res

        if energy <= 1.2: clr, cat = "green", "Isento (< 1.2)"
        elif energy <= 8.0: clr, cat = "orange", "Categoria 2"
        elif energy <= 40.0: clr, cat = "red", "Categoria 4"
        else: clr, cat = "black", "PERIGO EXTREMO"

        c_res1, c_res2 = st.columns(2)
        c_res1.metric("Energia Incidente", f"{energy:.2f} cal/cm²")
        c_res2.metric("Fronteira (AFB)", f"{afb:.0f} mm")

        st.markdown(f"""
        <div style="background-color:{clr};color:white;padding:15px;border-radius:10px;text-align:center;margin-bottom:10px;">
            <h3 style='margin:0'>RISCO: {cat}</h3>
        </div>
        """, unsafe_allow_html=True)
        st.write(f"**Corrente de Arco Estimada:** {i_arc:.2f} kA")
        st.write(f"**Tipo de Invólucro:** {box_type}")
    else:
        st.error("Erro matemático: Combinação inválida de Tensão/Corrente.")

st.markdown("---")
st.subheader("📈 Análise Gráfica: Energia x Tempo")
if res:
    times = np.linspace(10, 1000, 50)
    energies = []
    for t in times:
        _, e, _, _ = calcular_core_ieee1584(voltage, ibf_ka, config_electrode, gap_mm, dist_mm, t, h_mm, w_mm, d_mm)
        energies.append(e)
    chart_data = pd.DataFrame({"Tempo (ms)": times, "Energia (cal/cm²)": energies})
    st.line_chart(chart_data, x="Tempo (ms)", y="Energia (cal/cm²)")